steps:
  - name: 'gcr.io/cloud-builders/mvn'
    id: 'Get Project Version'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        VERSION=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)
        echo $VERSION > /workspace/versions.txt



  - name: 'gcr.io/cloud-builders/docker'
    entrypoint: 'bash'
    args:
      - '-c'
      - 'docker build -t us-central1-docker.pkg.dev/eighth-saga-474816-a6/dataflow-docker-artifactory/gcs-etl-dataflow:latest .'

  - name: 'gcr.io/cloud-builders/docker'
    id: 'Build versioned image'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        VERSION=$(cat /workspace/versions.txt)
        docker build -t us-central1-docker.pkg.dev/eighth-saga-474816-a6/dataflow-docker-artifactory/gcs-etl-dataflow:$VERSION .

  - name: 'gcr.io/cloud-builders/docker'
    id: 'Push latest image'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        VERSION=$(cat /workspace/versions.txt)
        docker push us-central1-docker.pkg.dev/eighth-saga-474816-a6/dataflow-docker-artifactory/gcs-etl-dataflow:latest

  - name: 'gcr.io/cloud-builders/docker'
    id: 'Push versioned image'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        VERSION=$(cat /workspace/versions.txt)
        docker push us-central1-docker.pkg.dev/eighth-saga-474816-a6/dataflow-docker-artifactory/gcs-etl-dataflow:$VERSION

  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - 'dataflow'
      - 'flex-template'
      - 'build'
      - 'gs://dataflow-bucket-quickstart/flex-template/gcs-etl-dataflow-flex-template.json'
      - '--image=us-central1-docker.pkg.dev/eighth-saga-474816-a6/dataflow-docker-artifactory/gcs-etl-dataflow:latest'
      - '--sdk-language=JAVA'

  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - '-c'
      - 'VERSION=$(cat /workspace/versions.txt)'
      - 'dataflow'
      - 'flex-template'
      - 'build'
      - 'gs://dataflow-bucket-quickstart/flex-template/gcs-etl-dataflow-flex-template-${VERSION}.json'
      - '--image=us-central1-docker.pkg.dev/eighth-saga-474816-a6/dataflow-docker-artifactory/gcs-etl-dataflow:$VERSION'
      - '--sdk-language=JAVA'

  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - 'storage'
      - 'cp'
      - 'src/main/resources/pipeline-options.json'
      - 'gs://dataflow-bucket-quickstart/gcs-etl-dataflow/pipeline-options/pipeline-options.json'

options:
  logging: CLOUD_LOGGING_ONLY

#options:
#  logging: GCS_ONLY
#  logsBucket: gs://dataflow-bucket-quickstart/cloud-build-logs/