steps:
  # Step 1: Extract Maven project version
  - name: 'gcr.io/cloud-builders/mvn'
    id: 'Get Project Version'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        mvn help:evaluate -Dexpression=project.version -q -DforceStdout > version.txt
        _IMAGE_VERSION=$(tail -n 1 version.txt)

  # Step 2: Build latest image
  - name: 'gcr.io/cloud-builders/docker'
    id: 'Build latest image'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        docker build -t us-central1-docker.pkg.dev/eighth-saga-474816-a6/dataflow-docker-artifactory/gcs-etl-dataflow:latest .

  # Step 3: Build versioned image
  - name: 'gcr.io/cloud-builders/docker'
    id: 'Build versioned image'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        _IMAGE_VERSION=$(tail -n 1 version.txt)
        docker build -t us-central1-docker.pkg.dev/eighth-saga-474816-a6/dataflow-docker-artifactory/gcs-etl-dataflow:${_IMAGE_VERSION} .

  # Step 4: Push latest image
  - name: 'gcr.io/cloud-builders/docker'
    id: 'Push latest image'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        docker push us-central1-docker.pkg.dev/eighth-saga-474816-a6/dataflow-docker-artifactory/gcs-etl-dataflow:latest

  # Step 5: Push versioned image
  - name: 'gcr.io/cloud-builders/docker'
    id: 'Push versioned image'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        _IMAGE_VERSION=$(tail -n 1 version.txt)
        docker push us-central1-docker.pkg.dev/eighth-saga-474816-a6/dataflow-docker-artifactory/gcs-etl-dataflow:${_IMAGE_VERSION}

  # Step 6: Build flex template for latest
  - name: 'gcr.io/cloud-builders/gcloud'
    id: 'Build flex template latest'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        gcloud dataflow flex-template build gs://dataflow-bucket-quickstart/flex-template/gcs-etl-dataflow-flex-template.json \
          --image=us-central1-docker.pkg.dev/eighth-saga-474816-a6/dataflow-docker-artifactory/gcs-etl-dataflow:latest \
          --sdk-language=JAVA

  # Step 7: Build flex template for versioned
  - name: 'gcr.io/cloud-builders/gcloud'
    id: 'Build flex template versioned'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        _IMAGE_VERSION=$(tail -n 1 version.txt)
        gcloud dataflow flex-template build gs://dataflow-bucket-quickstart/flex-template/gcs-etl-dataflow-flex-template-${_IMAGE_VERSION}.json \
          --image=us-central1-docker.pkg.dev/eighth-saga-474816-a6/dataflow-docker-artifactory/gcs-etl-dataflow:${_IMAGE_VERSION} \
          --sdk-language=JAVA

  # Step 8: Upload pipeline options
  - name: 'gcr.io/cloud-builders/gcloud'
    id: 'Upload pipeline options'
    args:
      - 'storage'
      - 'cp'
      - 'src/main/resources/pipeline-options.json'
      - 'gs://dataflow-bucket-quickstart/gcs-etl-dataflow/pipeline-options/pipeline-options.json'

options:
  logging: CLOUD_LOGGING_ONLY
